name: 'Packer Build'
description: 'Builds packer jobs'
inputs:
  working_dir:
    description: where to execute
    default: .
  git_tag_name:
    description: The tag prefix for git/build information
    default: git-info
  template_name:
    required: true
    description: The packer job name
  var_file:
    required: false
    description: a variable file to apply to the template
  validate_only:
    default: false
    description: Set to "true" if you want to only validate instead of build
  image_id_file: 
    description: |
     If set will update a variable file that is intended to 
     consumed by a downstream packer job.  Will set the image_id
     to the variable named in `image_id_variable_name`
  image_id_variable_name:
    default: parent_image_id
    description: the variable name to update .
  additional_info_file:
    default: /build-info.tpl.json
    description: |
     This file's json temlate gets rendered with dockerize and the
     environent, then is merged into your packer job. The default 
     behavior is to add git-info tags and to add in a manifest
     which can be used to more easily chain together builds.

  template_file:
    required: false
    desription: Use if the template file isn't simply the $template_name.json in the working dir
  
outputs:
  image-id:
    description: 'the ami created'
runs:
  using: 'docker'
  image: 'Dockerfile'