name: Packer Build
on:
  pull_request: 
    paths-ignore:
    - 'test/derivative**'
    - '.github/workflows/test-derivative.yml'
jobs:
  packer-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      id: packer_build
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
      with: 
        working_dir: test
        template: ubuntu
        image_id_file: derivative-vars.json
        image_id_variable_name: parent_image_id
    - name: Get Image id
      run: | 
        tmp=$(mktemp)
        echo "The image id was ${{steps.packer_build.outputs.image_id}}"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.5.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Update image id for derivatives
        COMMIT_AUTHOR_EMAIL: jmahowald@users.noreply.github.com
        COMMIT_AUTHOR_NAME: Josh Mahowald
        PULL_REQUEST_TITLE: '[AMI Info] Image ID'
        PULL_REQUEST_BODY: >
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        PULL_REQUEST_LABELS: report, automated pr
        PULL_REQUEST_ASSIGNEES: jmahowald
        PULL_REQUEST_REVIEWERS: jmahowald
        BRANCH_SUFFIX: short-commit-hash

