name: Packer Build
on:
  push: 
    paths:
    - '!test/derivative*'
    - '!.github/workflows/test-derivative.yml'
jobs:
  packer-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./
      id: packer_build
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
      with: 
        working_dir: test
        template: ubuntu
        image_id_file: derviate-vars.json
        image_id_variable_name: parent_image_id
    - name: Get Image id
      run: | 
        tmp=$(mktemp)
        echo "The image id was ${{steps.packer_build.outputs.image_id}}"

